# Generated by Django 4.0.6 on 2022-08-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(choices=[('AMEA', 'AMEA'), ('AMER', 'AMER'), ('AMS', 'AMS'), ('ANZ', 'ANZ'), ('ANZIT', 'ANZIT'), ('ANZUK', 'ANZUK'), ('APAC', 'APAC'), ('APEC', 'APEC'), ('APJ', 'APJ'), ('APMA', 'APMA'), ('APSG', 'APSG'), ('AU', 'AU'), ('ASEAN', 'ASEAN'), ('AUKUS', 'AUKUS')], default='AMEA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=10)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.region')),
            ],
        ),
    ]
